ALTER TABLE doc_files 
ADD COLUMN cover_url varchar(255) DEFAULT NULL COMMENT '封面URL',
ADD COLUMN category enum('SCIENCE_TECH', 'EDUCATION', 'LIFE_ENCYCLOPEDIA', 'PERSONAL_GROWTH', 'CHILDREN_EDUCATION', 'NOVEL', 'COMPUTER', 'BIOGRAPHY', 'FINANCE', 'OTHER') DEFAULT NULL COMMENT '分类',
ADD COLUMN learner_count int DEFAULT 0 COMMENT '学习人数',
ADD COLUMN author varchar(100) DEFAULT NULL COMMENT '作者',
ADD COLUMN publish_status enum('UNPUBLISHED','PUBLISHED') DEFAULT 'UNPUBLISHED' COMMENT '发布状态';
